# Generated by Django 3.2 on 2021-05-11 23:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontoffice', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proprietaire',
            old_name='cnl',
            new_name='cne',
        ),
    ]
